name             'pertino'
maintainer       'Mike Fiedler'
maintainer_email 'miketheman@gmail.com'
license          'MIT'
description      'Provides primitives for installing pertino-client'
long_description 'Provides primitives for installing pertino-client package'
version          '0.1.0'

depends 'apt'
depends 'yum'
